openapi: 3.0.1
info:
  title: Voucher Partner API
  version: 1.0.1
servers:
  - url: 'http://localhost:8087/api'
    description: Development server
  - url: 'https://localhost:8087/api'
    description: Development server with TLS Profile
paths:
  /voucher/allocation:
    post:
      tags:
        - voucher
      summary: Customer voucher allocation
      operationId: issueVoucher
      description: Reserve a voucher for a customer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoucherAllocationRequest'
      responses:
        '200':
          description: Sucessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherAllocationResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
  /voucher/return/{voucherId}:
    put:
      tags:
        - voucher
      summary: Return a voucher which was issued
      operationId: returnVoucher
      description: Return a voucher which was issued
      parameters:
        - name: voucherId
          in: path
          required: true
          description: The original wigroup voucher id or VP_VOUCHER.ID used to issued the voucher
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoucherReturnRequest'
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherReturnResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
  /product/validation/{productId}:
    get:
      tags:
        - product
      summary: Check whether the given voucher based product has stock.
      operationId: validateVoucher
      description: Check whether the given voucher based product has stock
      parameters:
        - name: productId
          in: path
          required: true
          description: The original wigroup voucher id or VP_VOUCHER.ID used to issued the voucher
          schema:
            type: string
        - name: origin
          in: query
          required: true
          description: origin identifier
          schema:
            type: string
        - name: campaign
          in: query
          required: true
          description: campaign identifier
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductValidationResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
  /product/list:
    get:
      tags:
        - product
      summary: Retrieves a list of all the voucher based products
      operationId: getProductList
      description: Retrieves a list of all the voucher based products
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
  /voucher/redemption/{voucherId}:
    post:
      tags:
        - voucher
      summary: Return a voucher which was issued
      operationId: redeemVoucher
      description: Redeem a voucher which was issued
      parameters:
        - name: voucherId
          in: path
          required: true
          description: Issues a new voucher code against a gift card which has had a partial redemption
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoucherRedemptionRequest'
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherRedemptionResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
  /voucher/balance/{voucherid}:
    get:
      tags:
        - voucher
      summary: Retrieves the current balance for a Wigroup giftcard.
      operationId: voucherbalance
      description: Check the current balance for given voucher based on the voucherid
      parameters:
        - name: voucherid
          in: path
          required: true
          description: the id of the issued gift card
          schema:
            type: integer
        - name: origin
          in: query
          required: true
          description: origin identifier
          schema:
            type: string
        - name: campaign
          in: query
          required: true
          description: campaign identifier
          schema:
            type: string
      responses:
        '200':
          description: Sucessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherBalanceResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
  /voucher/validation/{couponId}/{productId}:
    get:
      tags:
        - voucher
      summary: Checks validity of WiGroup vouchers being requested for refund
      operationId: voucherValidation
      description: Checks validity of WiGroup vouchers being requested for refund
      parameters:
        - name: couponId
          in: path
          required: true
          description: WiGroup Coupon Id
          schema:
            type: integer
        - name: productId
          in: path
          required: true
          description: Product Identifier
          schema:
            type: string

      responses:
        '200':
          description: Sucessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherValidationResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
  /campaign/list:
    get:
      tags:
        - campaign
      summary: Retrieves a list of all the campaigns
      operationId: getCampaignList
      description: Retrieves a list of all the campaigns
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignListResponse'
        '204':
          description: No content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
components:
  schemas:
    VoucherAllocationRequest:
      type: object
      properties:
        origin:
          description: Origin Identifier
          type: string
        productId:
          description: Product identifier
          type: string
        subIdType:
          description: Subscriber type, either VS, OM or Vodapay
          type: string
          enum: [VP, OM, VS, VK]
        subId:
          description: Subcriber Id Type
          type: string
        msisdn:
          description: Subcriber Id Type
          type: string
        campaign:
          description: campaign identifier
          type: string
        trxId:
          description: Subcriber Id Type
          type: string
        cost:
          description: Subcriber Id Type
          type: number
        value:
          description: Subcriber Id Type
          type: number
      required:
        - origin
        - productId
        - subIdType
        - subId
        - msisdn
        - campaign
        - trxId
        - cost
        - value
    VoucherAllocationResponse:
      type: object
      properties:
        voucherId:
          description: The unique id which shall be logged by CP-VOUCHERS for tracing
          type: integer
          format: int64
        voucherCode:
          description: >-
            The voucher
          type: string
        voucherDescription:
          description: >-
            The description of the voucher which was reserved, eg 'R50 Nando's
            voucher'
          type: string
        voucherType:
          description: The Type, eg GiftCard, OnlineVoucher
          type: string
        voucherCategory:
          description: 'The categor, eg food'
          type: string
        voucherVendor:
          description: "The vendor, eg Nando's"
          type: string
        collectPoint:
          description: An optional field that indicates where the voucher can be redeemed
          type: string
        expiryDate:
          description: The date by which the voucher has to be redeemed
          type: string
          format: date-time
        trxId:
          description: The incoming trxId
          type: string
        encryptedYN:
          description: 'Indicates Whether the returned voucher code is encrypted'
          type: string
    VoucherReturnRequest:
      type: object
      properties:
        productId:
          description: The product being returned
          type: string
        reason:
          description: The reason for the cancellation/return
          type: string
        msisdn:
          description: The 11 digit msisdn of the original transaction
          type: string
        trxId:
          description: Transaction Id Type
          type: string
      required:
        - productId
        - reason
        - msisdn
        - trxId
    VoucherReturnResponse:
      type: object
      properties:
        voucherId:
          description: The unique voucher id/seq
          type: integer
          format: int64
        voucherDescription:
          description: >-
            The description of the voucher which was reserved, eg 'R50 Nando's
            voucher'
          type: string
        trxId:
          description: The incoming trx id
          type: string
    ProductValidationResponse:
      type: object
      properties:
        voucherType:
          description: The Type, eg GiftCard, OnlineVoucher
          type: string
        voucherCategory:
          description: 'The categor, eg food'
          type: string
        voucherDescription:
          description: >-
            The description of the voucher which was reserved, eg 'R50 Nando's
            voucher'
          type: string
        voucherQuantity:
          description: 'The available vouchers'
          type: number
        voucherVendor:
          description: 'The vendor, eg Nandos'
          type: string
        minExpiry:
          description: 'The minimum expiry date'
          type: string
          format: date-time
    VoucherRedemptionRequest:
      type: object
      properties:
        origin:
          description: Origin Identifier
          type: string
        campaign:
          description: campaign identifier
          type: string
      required:
        - origin
        - campaign
    VoucherRedemptionResponse:
      type: object
      properties:
        voucherCode:
          description: >-
            The voucher
          type: string
        expiryDate:
          description: The date by which the voucher has to be redeemed
          type: string
    VoucherBalanceResponse:
      type: object
      properties:
        balance:
          type: number
          description: remaining balance on the gift card
        issuedAmount:
          type: number
          description: The amount issued for the gift card
        redeemedAmount:
          type: number
          description: The amount redeemed from the gift card
        expiredAmount:
          type: number
          description: The amount expired from the gift card
        expiryDate:
          type: string
          description: the date the giftcard expires "2015-05-25T23:59:59+0200"
    ProductListResponse:
      type: array
      items:
        type: object
        properties:
          productId:
            type: string
            description: Product Identifier
          description:
            type: string
            description: Description
          type:
            type: string
            description: Type
            enum: [Voucher,GenericVoucher,OnlineVoucher,OnlineGiftcard]
          category:
            type: string
            description: Category
          vendor:
            type: string
            description: Vendor
          extId:
            type: string
            description: The id/SKU of this product on the external system. Eg the campaign Id on Wigroup
          extSystem:
            type: string
            description: The external system being used for the issuing of real time vouchers
          validityPeriod:
            type: string
            description: The default validity period in days, relative to the date of issue
          cacheQuantity:
            type: string
            description: The number of vouchers to load into cache when the cache is depleted.
          encryptedYN:
            type: string
            description: Whether the voucher code should be encrypted in the database. Should always be Y
          extSyncSys:
            type: string
            description: Whether the stock levels in VP_VOUCHERS should be synced at certain intervals with another system such as Magento
    CampaignListResponse:
      type: array
      items:
        type: object
        properties:
          campaignId:
            type: string
            description: Campaign Identifier
          campaignName:
            type: string
            description: The unique name of the campaign
          startDate:
            type: string
            format: date
            description: The start date/time of the campaign
          endDate:
            type: string
            format: date
            description: The end date/time of the campaign
    VoucherValidationResponse:
      type: object
      properties:
        couponId:
          type: number
          description: The unique coupon id/seq
        description:
          type: string
          description: Description
        voucherAmount:
          type: number
          description: Voucher Amount
        status:
          type: string
          description: Status
        createDate:
          type: string
          format: date
        msisdn:
          type: string

    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: >
            An absolute URI that identifies the problem type.  When
            dereferenced,

            it SHOULD provide human-readable documentation for the problem type

            (e.g., using HTML).
          default: 'about:blank'
          example: 'https://zalando.github.io/problem/constraint-violation'
        title:
          type: string
          description: >
            A short, summary of the problem type. Written in english and
            readable

            for engineers (usually not suited for non technical stakeholders and

            not localized);
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: >
            The HTTP status code generated by the origin server for this
            occurrence

            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          format: uri
          description: >
            An absolute URI that identifies the specific occurrence of the
            problem.

            It may or may not yield further information if dereferenced.
  responses:
    Problem:
      description: >-
        error occurred - see status code and problem object for more
        information.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
