stages:
    - build

build:
  stage: build
  variables:
    UPSTREAM_PROJECT: $CI_PROJECT_NAME
    UPSTREAM_BRANCH: $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always  
  trigger:
    include:
    - project: 'vodacomsa/common-cicd-configs'
      file: '/trigger.gitlab-ci.yml'
