/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.vodacom.cvm.client.wigroup.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import za.co.vodacom.webfrontend.client.wigroup.model.GiftcardCampaignsResponse;

import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-10T13:34:34.750589900+02:00[Africa/Johannesburg]")
@Validated
@Tag(name = "Giftcardcampaigns", description = "the Giftcardcampaigns API")
public interface GiftcardcampaignsApi {

    /**
     * GET /giftcardcampaigns/{id} : returns all the active Gift Card campaigns which can be issue against
     * returns all the active Gift Card campaigns
     *
     * @param id The original wigroup voucher id or VP_VOUCHER.ID used to issued the voucher (required)
     * @return Successful Operation (status code 200)
     *         or No content (status code 204)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Method Not Allowed (status code 405)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "retrieveGiftcardCampaign",
        summary = "returns all the active Gift Card campaigns which can be issue against",
        tags = { "giftcardcampaigns" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful Operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GiftcardCampaignsResponse.class))
            }),
            @ApiResponse(responseCode = "204", description = "No content"),
            @ApiResponse(responseCode = "400", description = "Bad Request"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Method Not Allowed"),
            @ApiResponse(responseCode = "500", description = "Internal Server Error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/giftcardcampaigns/{id}",
        produces = "application/json"
    )
    ResponseEntity<GiftcardCampaignsResponse> retrieveGiftcardCampaign(
        @Parameter(name = "id", description = "The original wigroup voucher id or VP_VOUCHER.ID used to issued the voucher", required = true) @PathVariable("id") Long id
    );

}
